### ISSUE TITLE
TBC Classic support

### ISSUE THREAD

**Issue by Glaived** [bytespire/ItemTooltipProfessionIcons#4]
I haven't found any errors yet using the Classic (Vanilla) version of the addon, on the TBC Classic client.

So it is possible to add this addon as compatible for the TBC Classic client version.

**Comment by bytespire** [comment]
I am updating the item database to support TBC items within the next 24 hours

**Comment by bytespire** [comment]
I added support for JC and the TBC items however I dont have the client installed to test the changes. Anyone able to check if the icons are visible? I still need to update the config dialog before publishing a release
