### ISSUE TITLE
Separate zips for vanilla/classic/bcc

### ISSUE THREAD

**Issue by austen0** [bytespire/ItemTooltipProfessionIcons#5]
Including separate zips for each version in the github releases will make it easier to download/update the mod without Overwolf/Curseforge. Can be automated with github actions and the [BigWigs releaser](https://github.com/BigWigsMods/packager/wiki/GitHub-Actions-workflow).

**Comment by bytespire** [comment]
So this will list a zip for each version under "Assets" for the release?

**Comment by austen0** [comment]
Yep, something like this format would be great so that all variants can easily be fetched from the release tagged `latest`:
```
ItemTooltipProfessionIcons-bcc.zip
ItemTooltipProfessionIcons-classic.zip
ItemTooltipProfessionIcons-retail.zip
```

**Comment by bytespire** [comment]
I just learnt how to setup & customise workflows/actions, this is really helpful at structuring the files, wish I knew about this before I created a separate repository for the retail version.
Do you know if its possible to prevent the packager from adding a change log file to the zips?

**Comment by austen0** [comment]
~~Maybe you can add this to your `.pkgmeta`?~~
~~`manual-changelog:`~~
~~`  filename: /dev/null`~~

Nevermind, this definitely will not work.

**Comment by bytespire** [comment]
I tried defining a manual changelog and adding it to `ignore:` within the `.pkgmeta` which causes the packager to generate a changelog file. 

The separate zips are now available.

**Comment by austen0** [comment]
Thanks for implementing this!
