### ISSUE TITLE
Classic Era Update 1.15.0 (Season of Discovery)

### ISSUE THREAD

**Issue by maximus210793** [bytespire/ItemTooltipProfessionIcons#7]
Hi,
first of all, I want to say great adddon!
Could you update it to the latest Classic Era Game  Version of 1.15.0 (Season of Discovery)?
Would be awesome, thanks a lot in advance!

**Comment by bytespire** [comment]
Yea I'll update it soon, do you know if SoD contains any new professions changes?

**Comment by bytespire** [comment]
I updated to 1.15.0 and added the SoD items
